// Canvas actions

export const UPDATE_OBJECT = 'UPDATE_OBJECT';
export const UPDATE_GROUP_OBJECT = 'UPDATE_GROUP_OBJECT';
export const UPDATE_CURRENT_OBJECT = 'UPDATE_CURRENT_OBJECT';
export const DELETE_OBJECT = 'DELETE_OBJECT';
export const UPDATE_PANNING_POSITION = 'UPDATE_PANNING_POSITION';

// User actions

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';



// user-canvas actions


export const LOAD_CANVASES = 'LOAD_CANVASES';
export const LOAD_CANVASES_SUCCESS = 'LOAD_CANVASES_SUCCESS';
export const LOAD_CANVASES_FAIL = 'LOAD_CANVASES_FAIL';


export const POST_CANVAS_SUCCESS = 'POST_CANVAS_SUCCESS';
export const UPDATE_CANVAS_SUCCESS = 'UPDATE_CANVAS_SUCCESS';

export const DELETE_CANVAS_WITH_ID_SUCCESS = 'DELETE_CANVAS_WITH_ID_SUCCESS';

export const LOG_OUT = 'LOG_OUT';
