// Canvas actions

export const UPDATE_OBJECT = 'UPDATE_OBJECT';
export const UPDATE_GROUP_OBJECT = 'UPDATE_GROUP_OBJECT';
export const UPDATE_CURRENT_OBJECT = 'UPDATE_CURRENT_OBJECT';
export const DELETE_OBJECT = 'DELETE_OBJECT';
export const UPDATE_PANNING_POSITION = 'UPDATE_PANNING_POSITION';

// User actions

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';





